[coordinator]
ip = "127.0.0.1"
port = "50052"

[node]
name = "maple-virtual-machine"

[node.storage]
name = "vgdata"
device = "sda"
level ="SSD"
space = 100
write = 200
read = 300

[watcher]
pauseTime = 1