[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "go.etcd.io/etcd"
  version = "3.3.13"

[[constraint]]
  branch = "master"
  name = "k8s.io/api"

[[constraint]]
  branch = "master"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "12.0.0"


[[constraint]]
  name = "github.com/docker/docker"
  branch = "master"

[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "v1.0.0"


[prune]
  go-tests = true
  unused-packages = true

